# Azure DevOps Pipeline using Template-based Architecture
# Main pipeline file that leverages reusable templates

trigger:
- none

pr:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'AI Testing'

stages:
- stage: Test
  displayName: 'Python Testing'
  jobs:
  - job: PythonTests
    displayName: 'Python 3.11 Tests'
    steps:
    - template: ../templates/python-test-template.yml
      parameters:
        pythonVersion: '3.11'
        enableCoverage: true