name: Python Tests

on:
  workflow_dispatch:
    inputs:
      test_filter:
        description: 'Test filter pattern (optional)'
        required: false
        default: ''
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Chrome DevTools MCP
      run: npm install chrome-devtools-mcp@latest
    
    - name: Create virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
    
    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
    
    - name: Run tests
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
      run: |
        source venv/bin/activate
        if [ -n "${{ inputs.test_filter }}" ]; then
          pytest --tb=short --verbose --junitxml=test-results.xml -k "${{ inputs.test_filter }}"
        else
          pytest --tb=short --verbose --junitxml=test-results.xml
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xml
    
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false